<h2>Hrm, what's this?</h2>
<p>This is your dashboard! Well, atleast that's what we are calling it for now. Your dashboard is a place you can come to find a complete overview of all of the things you enjoy about World of Warcraft!</p>
<p>Few quick notes about using your dashboard:</p>
<li>Your dashboard is filled with things your following.</li>
<li>You can unfollow or follow anything on the site to add it to this page.</li>
<li>Have a question? Ask it and tag it "<a href='/tag/27/epicadvice-com'>epicadvice.com</a>" and "dashboard"!</li>
<p>Think of it as functioning like Twitter, whatever you follow (from people to things to tags) will be the subject matter of what appears here.</p>