<? $this->context()->prepend('
<h2>Words from Fans</h2>
<hr>
<h3>From fans of EpicAdvice, the <a href="http://www.pokerlistings.com/online-poker-rooms">Poker Online Guide</a> PokerListings.com:</h3>
<p>"We\'ve been following the development of the wonderful project, and as dedicated gamers as well as poker editors, we can say that this has evolved into a great gaming resource with unprecedented amount of helpful material. Thanks for providing gamers with all this!" - Claire, <a href="http://www.pokerlistings.com/texas-holdem">texas holdem</a> editor at our supporters, the poker resource <a href="http://www.pokerlistings.com">PokerListings.com</a>.</p>
')?>
<div id="mainbar">
<div class="post-text" style="margin-left: 60px;">
<h1>About EpicAdvice.com</h1>
<p>(This material is outdate, and will be updated soon)</p>
<p><b>EpicAdvice.com</b> is a website built to serve the <a href="http://www.worldofwarcraft.com/">World of Warcraft</a> community by answering their questions. The existence of WoW (World of Warcraft) websites is astronomical, but none of them that we were able to find fit the Q&amp;A needs of the community. There are hundreds of sites that supply news, products, discussion and information out there, and they are all sites we visit daily, but one key aspect was missing: Questions and Answers. We accomplish this on EpicAdvice.com using the <a href="http://www.stackexchange.com/">StackExchange</a> engine (<a href="http://www.stackexchangesites.com/">like many others</a>) and some slight javascript trickery for enchanced features, many kudos to <a href="http://www.fogcreek.com/">Fog Creek Software</a> for making this possible.</p>

<p>Before <b>EpicAdvice.com</b>, the only place you really could go to ask a specific question, about a specific topic, was one of many Forums or Bulletin Boards. Discussions broke out, flame wars were started, and that question never really got answered. Well, that's what we are here for. The users of EpicAdvice.com are the ones asking and answering all of these questions, and no we do not have a staff of trained monkeys with keyboards. By asking and answering questions, user's build up their reputation.  Providing good questions and answers will build your reputation. You can also lose reputation by posting things irrelevant, not useful to the question, or effortless questions and answers. So when you get an answer from someone with 20k reputation, you can rest assured that they've contributed a lot of their knowledge to the website, and people agreed with them. </p>

<p><b>EpicAdvice.com</b> organizes questions using tags that are relevant to the content. You can choose to enter tags you are "Interested in" and tags you wish to "Ignore", and the system will hide or show questions more relevant to your interests in the game. These tags are all search-able, mash-able and kept in check by our moderators. Getting used to using the tags will save you <b>much</b> time while you are navigating around.</p>

<p>As you earn reputation with <b>EpicAdvice.com</b>, either by asking good questions (non-"Community Wiki") or providing great answers, you will gain more moderation power over the content of the site. If you know what your talking about, you contribute more, you earn more. Simple concept! On the other end of the spectrum, posting irrelevant material, starting flame wars or just in general acting like a jerk, will cause you to lose permissions you may have earned on the site and your hard earned "Reputation Points". With enough reputation, a user essentially becomes a moderator; able to edit questions and answers, tags and keep tabs on other users' actions.</p>

<p>All in all, the community we aim to build will be a reputable source of information, in and out of the game. We would love for Blizzard Entertainment to get involved if they choose to do so, I mean what would be better than asking an Epic Question on EpicAdvice.com, and getting a <font color="#00C0FF"><b>blue</b></font> post as advice? Maybe even we'd let them be <font color="#A335EE"><b>epic</b></font> on EpicAdvice.com, instead of being <font color="#00C0FF"><b>rare</b></font>!</p>

<h1>Our Goal</h1>

<p>We want to provide you with the best platform to ask a question about World of Warcraft and receive the answer you are looking for. We hope to implement many more user-interface improvements that will allow you to ask these questions easier or explain your answer better. After all, sometimes Epic Advice could be in the form of a diagram or model.</p>

<p>If you have any questions or comments, drop by the <a href="/page/contact">Contact Page</a> to drop us a line!</p>
</div>
</div>