<? $this->context()->prepend('
<h2>Reviews &amp; Comments</h2>
<h3>From fans of EpicAdvice, the <a href="http://www.pokerlistings.com/online-poker-rooms">Poker Online Guide</a> PokerListings.com:</h3>
"We\'ve been following the development of the wonderful project, and as dedicated gamers as well as poker editors, we can say that this has evolved into a great gaming resource with unprecedented amount of helpful material. Thanks for providing gamers with all this!" - Claire, <a href="http://www.pokerlistings.com/texas-holdem">texas holdem</a> editor at our supporters, the poker resource <a href="http://www.pokerlistings.com">PokerListings.com</a>.
')?>

<div class="post-text" style="margin-left: 60px;">
<h2>Frequently Asked Questions</h2>

<h3>What kind of questions can I ask here?</h3>

<p><strong>World of Warcraft questions, of course!</strong> As long as your question is:</p>

<ul>
    <li>detailed and specific</li>
    <li>written clearly and simply</li>
    <li>of interest to at least one other person somewhere</li>
</ul>

<p>
    ... it is welcome here. No question is too trivial or too "newbie". Oh yes, and
    it should be about <strong>World of Warcraft</strong>.
</p><p>
    Please look around to see if your question has already been asked (and maybe even
    answered!) <em>before</em> you ask. If you end up asking a question that has been
    asked before, that is OK and deliberately allowed. Other users will hopefully edit
    in links to related or similar questions to help future visitors find their way.
</p><p>
    It's also perfectly fine to ask and answer your own question, but pretend
    you're on <a href="http://en.wikipedia.org/wiki/Jeopardy%21">Jeopardy</a>: phrase
    it in the form of a question.
</p>

<h3>What kind of questions should I <i>not</i> ask here?</h3>
<p>
    <strong>Avoid asking questions that are subjective, argumentative, will start a flame-war
        or require extended discussion.</strong> This is not a discussion board, this
    is a place for questions that can be answered!
</p><p>

</p><h3>
    Be nice.</h3>
<p>
    <strong>Treat others with the same respect you'd want them to treat you.</strong>
    We're all here to learn together. Be tolerant of others who
    may not know everything you know. Bring your sense of humor.
</p>


<h3>Be honest.</h3>
<p>
    Above all, be honest. If you see misinformation, vote it down. Insert comments indicating
    what, specifically, is wrong. Even better — edit and improve the information!
    Provide stronger, faster, superior answers of your own!
</p>

<h3>Do I have to log in or create an account?</h3>
<p>
    Nope. You can answer and ask questions to your heart's content as an anonymous user,
    much like <a href="http://www.wikipedia.org/">Wikipedia</a>. However, there are
    some things you won't be able to do on the site without registering. But it's <a href="/users/login">easy to register</a> if you want to. All you need is an
    <a href="http://openid.net/what/">OpenID</a> account.
</p>

<h3><a name="reputation"></a>What is reputation?</h3>
<p>
    Reputation is completely optional. Normal use of EpicAdvice.com — that is,
    asking and answering questions — does not require any reputation whatsoever.
</p><p>
    Remember, EpicAdvice.com is run by <em>you!</em> If you want to help us run the site,
    you'll need reputation first. Reputation is a (very) rough measurement of <strong>
        how much the EpicAdvice.com community trusts you</strong>. Reputation is never
    given, it is <i>earned</i> by convincing other users that you know
    what you're talking about.
</p><p>
    Here's how it works: if you post a good question or helpful answer, it will be voted
    up by your peers: you gain <strong>10</strong> reputation points. If you post something that's
    off topic or incorrect, it will be voted down: you lose <b>2</b> reputation points.
    You can earn up to <strong>200</strong> reputation per day, but no more. (Note that votes
    for any posts marked "community wiki" do not generate reputation.)
</p><p>
    Amass enough reputation points and EpicAdvice.com will allow you to go beyond simply
    asking and answering questions:
</p>
<table id="replevels">
    <tbody><tr><td class="x">15</td><td>Vote up</td></tr>
    <tr><td class="x">15</td><td>Flag offensive</td></tr>
    <tr><td class="x">50</td><td>Leave comments</td></tr>
    <tr><td class="x">100</td><td>Vote down (costs 1 rep), edit community wiki posts</td></tr>
    <tr><td class="x">200</td><td>Reduced advertising</td></tr>
    <tr><td class="x">250</td><td>Vote to close or reopen your questions, create new tags</td></tr>
    <tr><td class="x">500</td><td>Retag questions</td></tr>
    <tr><td class="x">2000</td><td>Edit other people's posts</td></tr>
    <tr><td class="x">3000</td><td>Vote to close or reopen any questions</td></tr>
    <tr><td class="x">10000</td><td>Delete closed questions, access to moderation tools</td></tr>
</tbody></table>

<p>
    At the high end of this reputation spectrum there is little difference between users
    with high reputation and moderators. That is very much intentional. We don't run
    EpicAdvice.com. The community does.
</p>

<h3><a name="bounty"></a>What if I don't get a good answer?</h3>
<p>
    In order to get good answers, you have to put some effort into the question. Edit
    your question to provide status and progress updates. Document your own continued
    efforts to answer your question. This will naturally bump your question and get
    more people interested in it.
</p><p>
    If, after two days, you <strong>still</strong> don't have an answer you like, you can 
    <strong>offer a bounty</strong>. Slice off a bit of your own
    hard-earned reputation -- anywhere from 50 to 500 -- and attach it to the question
    as a bounty. We'll even throw in 50 reputation to sweeten the deal. The bountied
    question will appear with a special icon in all question lists, and it will also
    be visible on the <a href="/?tab=featured">home page Featured</a> tab.
</p><p>
    Once initiated, the bounty period lasts seven days. If you mark an accepted answer,
    your bounty is awarded to the answerer (do note that accepted bounty answers are
    permanent and cannot be changed). If you do not accept an answer in seven days,
    the top voted answer will automatically become the accepted answer, and half your
    bounty will be awarded to that answer. You will always give up the amount of reputation
    specified in the bounty, so if you start a bounty, be sure to follow up and accept
    the best answer!
</p><p>
    Of course, bounty awards, like all accepted answers, are immune to the daily reputation
    cap and community wiki mode.
</p>

<h3>Other people can edit my stuff?!</h3>
<p>
    Like Wikipedia, <strong>this site is collaboratively edited</strong>.
    If you are not comfortable with the idea of your questions and answers being edited
    by other trusted users, this may not be the site for you.
</p>
</div>
