<div class='column-content-2c inline-flow rounded'>
	<?= $this->layout()->content ?>
</div>
<div class='column-sidebar-2c inline-flow rounded'>
	<? if($profile = EpicDb_Auth::getInstance()->getUserProfile()): ?>
	<div class="sidebar-widget rounded shadowy">
		<p>Welcome,</p>
		<h2>
			<?= $this->profileLink($profile) ?> 
			<? if($profile->reputatoin): ?>(<?= $profile->reputation?>)<? endif; ?>
		</h2>
		<p>You have <a href="#">7 notifications</a> and <a href="#">21 updates</a> waiting review.</p>
	</div>
	<? else: ?>
	<div class="sidebar-widget rounded shadowy">
		<img alt="EpicAdvice.com" src="http://profile.epicadvice.com/images/design/EA300.png">
		<h1 style="text-align: center"> 
			World of Warcraft
		</h1>
		<h2 style="text-align: center">
			Questions and Answers
		</h2>
		<p class="text-medium">
			Welcome to EpicAdvice.com, please take a look around some of the <a href="/tags">popular tags</a> or the <a href="http://epicadvice.com/questions/tagged/faq">FAQ</a>. 
			Also considering <a href="/user/login">logging in</a> with your preferred method to participate in the discussion!
		</p>
	</div>
	<? endif; ?>
	
	<div class="sidebar-widget rounded shadowy">
		<h2 style="text-align: center">
			Recent News
		</h2>
	</div>
	
	<div class="sidebar-widget rounded shadowy">
		<h2 style="text-align: center">
			Achievements Earned
		</h2>
	</div>

	<div class="sidebar-widget rounded shadowy">
		<h2 style="text-align: center">
			Popular Topics
		</h2>
	</div>

	<? if(APPLICATION_ENV == 'production'):?>
	<div class="sidebar-widget rounded shadowy">
		<!--JavaScript Tag // Tag for network 5223: Gamer DNA Media // Website: EpicAdvice // Page: EpicAdvice.com // Placement: EpicAdvice.com-Above-300 x 250 (1899221) // created at: Mar 10, 2011 12:03:50 PM-->
		<script language="javascript">
		<!--
		if (window.adgroupid == undefined) {
			window.adgroupid = Math.round(Math.random() * 1000);
		}
		document.write('<scr'+'ipt language="javascript1.1" src="http://helios.gamerdna.com/addyn|3.0|5223|1899221|0|170|ADTECH;loc=100;target=_blank;key=key1+key2+key3+key4;grp='+window.adgroupid+';misc='+new Date().getTime()+'"></scri'+'pt>');
		//-->
		</script><noscript><a href="http://helios.gamerdna.com/adlink|3.0|5223|1899221|0|170|ADTECH;loc=300;key=key1+key2+key3+key4" target="_blank"><img src="http://helios.gamerdna.com/adserv|3.0|5223|1899221|0|170|ADTECH;loc=300;key=key1+key2+key3+key4" border="0" width="300" height="250"></a></noscript>
		<p class="text-small" style="margin: 0; text-align: center; font-weight: bold;">EpicAdvice.com Sponsors</p>
	</div>
	<? endif; ?>

</div>