<div id="footer">
	<?= $this->render("awesome/_cc.phtml"); ?>
	<p>
		<a href="/questions">Questions</a>
	</p>
	<p>
		<a href="/about">About</a>
		| 
		<a href="/contact">Contact</a>
		| 
		<a href="/help">Help</a>
	</p>
	<p class="copyright">&copy; 2009 - 2011 <a href="http://epicadvice.com">EpicAdvice.com</a></p>
	<p>This site is in not endorsed by or affiliated with Blizzard Entertainment.</p>
	<p>Game content and materials copyright LICENSOR. All Rights Reserved.</p>
</div>