<? if($profile = EpicDb_Auth::getInstance()->getUserProfile()): ?>
	<? if(!$profile->reputation || $profile->reputation < 200): ?>
		<div class="ad-pre-answer">
			<!--JavaScript Tag // Tag for network 5223: Gamer DNA Media // Website: EpicAdvice // Page: EpicAdvice.com // Placement: EpicAdvice.com-Above-728 x 90 (1899222) // created at: Mar 10, 2011 12:04:08 PM-->
			<script language="javascript">
			<!--
			if (window.adgroupid == undefined) {
				window.adgroupid = Math.round(Math.random() * 1000);
			}
			document.write('<scr'+'ipt language="javascript1.1" src="http://helios.gamerdna.com/addyn|3.0|5223|1899222|0|225|ADTECH;loc=100;target=_blank;key=key1+key2+key3+key4;grp='+window.adgroupid+';misc='+new Date().getTime()+'"></scri'+'pt>');
			//-->
			</script><noscript><a href="http://helios.gamerdna.com/adlink|3.0|5223|1899222|0|225|ADTECH;loc=300;key=key1+key2+key3+key4" target="_blank"><img src="http://helios.gamerdna.com/adserv|3.0|5223|1899222|0|225|ADTECH;loc=300;key=key1+key2+key3+key4" border="0" width="728" height="90"></a></noscript>
			<!-- End of JavaScript Tag -->
			<h3>These advertisements are only displayed to non-users and users with less than 200 reputation.</h3>
		</div>
	<? endif; ?>
<? endif; ?>
<table id="question-<?= $this->question->id ?>">
	<tbody>
		<tr>
			<td class="votecell">
				<?= $this->voteWidget($this->question) ?>
			</td>
			<td>
				<div>
					<div class="post-meta">
						Posted on <?= $this->postLink($this->question, array("text" => $this->timeAgo($this->question->_created))) ?> by <?= $this->profileLink($this->question->tags->getTag('author'))?>
						<? if($this->question->touched && $this->question->touchedBy instanceOf EpicDb_Mongo_Profile_User): ?>
						, updated <?= $this->timeAgo($this->question->touched) ?> by <?= $this->profileLink($this->question->touchedBy) ?>
						<? endif; ?>
					</div>
					<div class="post-text rounded">
						<div style="min-height: 80px">
							<?= $this->question->body?>
						</div>
						<div class="post-controls ui-helper-clearfix">
							<?= $this->button(array(
								'action'=>'edit',
								'post'=>$this->question,
							), 'post', true, array(
								'icon' => 'pencil',
								'requirePriv' => 'edit',
							)); ?>
							<?= $this->button(array(
								'action'=>'answer',
								'post'=>$this->question,
							), 'post', true, array(
								'icon' => 'notice',
								'style' => 'float: right',
								'text' => 'Answer this Question',
								'requirePriv' => 'create',
							)); ?>
						</div>
					</div>
					<div class="post-taglist inline-flow">
						<div class="inline-flow">
							<h3>Question regarding...</h3>
						</div>
						<div class="post-moderate inline-flow">
							<a href="<?= $this->escape( $this->url(array(
								'action'=>'revisions',
								'post'=>$this->question,
							), 'post', true) ); ?>">History</a>
							<!-- <span>|</span>
							<a href="#">Link</a>
							<span>|</span>
							<a href="#">Link</a> -->
						</div>
						<div class="post-tags">
							<? foreach($this->question->tags as $tag): ?>
								<? if($tag->reason != 'tag') continue;?>
								<?= $this->card($tag->ref, array("class" => "medium-icon")) ?>
							<? endforeach; ?>
						</div>
					</div>
					<?= $this->card($this->question->tags->getTag('author'), array("class" => "wide"))?>
				</div>
			</td>
		</tr>
		<tr>
			<td class="votecell"></td>
			<td>
				<div class="post-comments">
					<div class="comments-container" id="comments-2978">
						<div class="comments">
							<table>
								<tbody>
									<? foreach($this->question->findComments() as $comment): ?>
										<?= $this->partial("./post/se/_comment.phtml", array("comment" => $comment)) ?>
									<? endforeach; ?>
								</tbody>
							</table>
						</div>
					</div>
					<?= $this->button(array(
						'action'=>'comment',
						'post'=>$this->question,
					), 'post', true, array(
						'icon' => 'reply',
						'text' => 'leave comment',
						'requirePriv' => 'create',
					)); ?>
				</div>
			</td>
		</tr>
	</tbody>
</table>