<div class="module rounded" id="good-question">
	<h1>
		<img alt="EpicAdvice.com" src="http://profile.epicadvice.com/images/design/EA300.png">
	</h1>
	<h2 style="color: #FFD440;">
		How to ask a "Good Question"
	</h2>
	<p style="font-size: 0.9em;line-height:1.25em">
		Asking a good question can be pretty difficult sometimes, luckily we've been at this for a while and have a few pointers for you to maximize the quality of the answers you'll receive! Follow this quick list to help those looking to help you.
	</p>
	<ul style="font-size: 0.9em; font-weight: normal;">
		<li>Try to sum up your question in a single, 120 character or less title.</li>
		<li>Make sure to let people know what you know</li>
		<li>Tell us what class, level and maybe even give us an armory link</li>
		<li>Take your time and use proper grammar, otherwise it takes time to decipher what your trying to say.</li>
		<li>Don't be afraid to admit if you don't know something</li>
	</ul>
</div>
<div class="module rounded" id="good-tags">
	<h2 style="color: #FFD440;">
		Tagging your Question
	</h2>
	<p style="font-size: 0.9em;line-height:1.25em">
		Tagging your question helps us channel questions to the users interested in specific topics. Is your question about a warrior spec? About a dungeon? A specific NPC or a specific Item? Make sure to tag it as such!
	</p>
</div>
