<div id="sidebar-top" class="porthole">
	<center>
		<? if(APPLICATION_ENV == 'production'):?>
		<!--JavaScript Tag // Tag for network 5223: Gamer DNA Media // Website: EpicAdvice // Page: EpicAdvice.com // Placement: EpicAdvice.com-Above-300 x 250 (1899221) // created at: Mar 10, 2011 12:03:50 PM-->
		<script language="javascript">
		<!--
		if (window.adgroupid == undefined) {
			window.adgroupid = Math.round(Math.random() * 1000);
		}
		document.write('<scr'+'ipt language="javascript1.1" src="http://helios.gamerdna.com/addyn|3.0|5223|1899221|0|170|ADTECH;loc=100;target=_blank;key=key1+key2+key3+key4;grp='+window.adgroupid+';misc='+new Date().getTime()+'"></scri'+'pt>');
		//-->
		</script><noscript><a href="http://helios.gamerdna.com/adlink|3.0|5223|1899221|0|170|ADTECH;loc=300;key=key1+key2+key3+key4" target="_blank"><img src="http://helios.gamerdna.com/adserv|3.0|5223|1899221|0|170|ADTECH;loc=300;key=key1+key2+key3+key4" border="0" width="300" height="250"></a></noscript>
		<? endif; ?>
		<!-- End of JavaScript Tag -->		<br>
		<b>What do the colors mean?</b>
		<br>
		<div style="margin-top: 5px;" class="status unanswered">
		  Green: No answers yet!
		</div>
		<div style="margin-top: 5px;" class="status answered">
		  Blue: Has answers, none accepted.
		</div>
		<div style="margin-top: 5px;" class="status answered-accepted">
		  Purple: Has an accepted answer.
		</div>
		<br>
	</center>
</div>