<div class="module newuser" id="welcome">
	<h1>
		<img alt="EpicAdvice.com" src="http://profile.epicadvice.com/images/design/EA300.png">
	</h1>
	<h2>
		World of Warcraft Questions and Answers
	</h2>
	<p style="font-size: 0.9em;line-height:1.25em">
		Welcome to EpicAdvice.com, please take a look around some of the <a href="/tags">popular tags</a> or the <a href="http://epicadvice.com/questions/tagged/faq">FAQ</a>
	</p>
</div>
