<div id="system-message" class="system-message-color rounded shadowy inline-flow">
	<h3>Looking for Help with EpicAdvice.com</h3>
	<p>We've recently published a new blog post explaining what's going on with EpicAdvice.com and are looking for someone to work with us to improve the site. If you're interested, have some ideas and want to know more, <a href="http://blog.epicadvice.com/2011/08/09/lfm-epicadvice-com-team-leader/">check out our blog post</a> and feel free to email us at <a href="mailto:team@epicadvice.com">team@epicadvice.com</a>. - Jesta</p>
</div>
<div id="system-half-banner" class="inline-flow">
	<a href='http://www.enjin.com/?ref=485091' target='_new'><img src="/images/ads/enjin.jpg" class="rounded center-shadow"/></a>
</div>