<?php if ($this->pageCount > 1): ?>
<div class="paginationControl">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
	<a href="/users?page=<?= $this->previous ?>">
		Previous
	</a> |
<?php else: ?>
	<span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
	<?php if ($page != $this->current): ?>
		<a href="/users?page=<?= $page ?>">
				<?php echo $page; ?>
		</a> |
	<?php else: ?>
		<?php echo $page; ?> |
	<?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
	<a href="/users?page=<?= $this->next ?>">
		Next &gt;
	</a>
<?php else: ?>
	<span class="disabled">Next</span>
<?php endif; ?>
</div>
<?php endif; ?>