<?php if ($this->header): ?>
  <tr>
    <th>E-Mail Address</th>
    <th>Name</th>
    <th>Options</th>
  </tr>
<?php else: ?>
  <tr class='user' id='user_<?= $this->user->id ?>'>
    <td><?= $this->escape($this->user->email) ?></td>
    <td><?= $this->escape($this->user->name) ?></td>
    <td><a href='<?= $this->url(array('controller'=>'user', 'action'=>'edit', 'id'=>$this->user->id)) ?>'>edit</a></td>
  </tr>    
<?php endif ?>