<div style="text-align: right">
	<?php if ($this->pageCount > 1): ?>
	<div class="paginationControl font-sans inline-flow">
	<!-- Previous page link -->
	<?php if (isset($this->previous)): ?>
		<div class="page-selector inline-flow rounded shadowy">
			<a href="?page=<?= $this->previous ?>">&lt;</a>
		</div>
	<?php endif; ?>

	<!-- Numbered page links -->
	<?php foreach ($this->pagesInRange as $page): ?>
			<?php if ($page != $this->current): ?>
				<div class="page-selector inline-flow rounded shadowy">
					<a href="?page=<?= $page ?>"><?php echo $page; ?></a>
				</div>
			<?php else: ?>
				<div class="page-selector selected inline-flow rounded shadowy">
					<?php echo $page; ?>
				</div>
			<?php endif; ?>
	
	<?php endforeach; ?>

	<!-- Next page link -->
	<?php if (isset($this->next)): ?>
	<div class="page-selector inline-flow rounded shadowy">
		<a href="?page=<?= $this->next ?>">&gt;</a>
	</div>
	<?php endif; ?>
	</div>
	<?php endif; ?>
	<div class="sortingControl inline-flow">
		<select class="sort-control">
			<option>Sort by...</option>
			<option value='newest'>Newest First</option>
			<option value='oldest'>Oldest First</option>
			<option value='highest-voted'>Highest Voted</option>
			<option value='lowest-voted'>Lowest Voted</option>
		</select>
		<script type="text/javascript" charset="utf-8">
			$(function() {
				$(".sort-control").bind('change', function() {
					window.location = '?sort='+$(this).val();
				});
			});
		</script>
	</div>
</div>