<div id="content">
	<div id="mainbar">
		<div id="subheader">
			<h2>Unanswered Questions</h2>
			<div id="tabs">
				<a href="#" class="youarehere">newest</a>
			</div>
		</div>
		<? foreach($this->questions as $question): ?>
			<?= $this->seQuestion($question); ?>
		<? endforeach; ?>
	</div>
	<div id="sidebar"> 
		<?= $this->render('./post/se/_sidebar-welcome.phtml') ?>
		<?= $this->render('./post/se/_sidebar-porthole.phtml') ?>
		<div style="padding-left:4px; padding-right:4px;" class="module" id="recent-tags">
			<h4 style="padding-left:4px;">Popular Tags</h4>
			<div>
				<? foreach($this->popularTags as $tag): ?>
					<a rel="tag" title="show questions tagged '<?= $tag['record']->name ?>'" class="post-tag" href="<?= $this->escape( $this->url(array(
						'record' => $tag['record']
					), 'record', true) ); ?>"><?= $tag['record']->name ?><? if((int)$tag['count'] > 1): ?><span class='text-small' style='color: #fff'> x<?= $tag['count'] ?></span><? endif; ?></a>
				<? endforeach; ?>
			</div>
		</div>  
		<div style="overflow:hidden;" id="recent-badges" class="module">
			<h4>Recent Badges</h4>
			<p style="text-align:right;">
				<a href="/badges">all badges »</a>
			</p>
		</div>  
		<?= $this->render("./post/se/_sidebar-porthole-low.phtml") ?>
	</div>
</div>
