<?php $this->headTitle(strip_tags($this->post->title)); ?>
<? 
	$this->context()->widget($this->render("_context/news.phtml"));
	if($relatedPosts = $this->post->getRelatedPosts()) {
		$this->context()->widget($this->partial("./_context/related-posts.phtml", array('posts' => $relatedPosts))); 		
	}
?>


<div id="question">
	<?= $this->render('./post/_question.phtml')?>
</div>
<div id="answers">
	<a name="sort-top"></a>
	<div id="answers-header">
		<div id="subheader">
			<h2><?= $this->post->findAnswers()->count() ?> Answer(s)</h2>
			<div id="answer-tabs">
				<strong>Sort by...</strong>
				<a title="Sort by Highest Voted Answers first" href="#" class="shadowy">votes</a>
				<a title="Sort by Highest Voted Answers first" href="#" class="shadowy">newest</a>
			</div>
		</div>
	</div>
	<? $first = true; // Used to specify the first banner in the loop of answers, crappy huh? :) ?>
	<? foreach($this->post->findAnswers() as $answer): ?>

		<?= $this->partial('./post/_answer.phtml', array('answer' => $answer)) ?>

		<? if(APPLICATION_ENV == 'production' && $first == true && $profile = EpicDb_Auth::getInstance()->getUserProfile()): ?>
			<? if(!$profile->reputation || $profile->reputation < 200): ?>
				<div class="ad-post-answer">
					<!--JavaScript Tag // Tag for network 5223: Gamer DNA Media // Website: EpicAdvice // Page: EpicAdvice.com // Placement: EpicAdvice.com-Below-728 x 90 (1900176) // created at: Mar 10, 2011 12:04:24 PM-->
					<script language="javascript">
					<!--
					if (window.adgroupid == undefined) {
						window.adgroupid = Math.round(Math.random() * 1000);
					}
					document.write('<scr'+'ipt language="javascript1.1" src="http://helios.gamerdna.com/addyn|3.0|5223|1900176|0|225|ADTECH;loc=100;target=_blank;key=key1+key2+key3+key4;grp='+window.adgroupid+';misc='+new Date().getTime()+'"></scri'+'pt>');
					//-->
					</script><noscript><a href="http://helios.gamerdna.com/adlink|3.0|5223|1900176|0|225|ADTECH;loc=300;key=key1+key2+key3+key4" target="_blank"><img src="http://helios.gamerdna.com/adserv|3.0|5223|1900176|0|225|ADTECH;loc=300;key=key1+key2+key3+key4" border="0" width="728" height="90"></a></noscript>
					<!-- End of JavaScript Tag -->
					<h3>These advertisements are only displayed to non-users and users with less than 200 reputation.</h3>
				</div>
			<? endif; ?>
			<? $first = false; // Don't show ads after the 1st answer ?>
		<? endif; ?>

	<? endforeach; ?>
</div>
<div id="form-quick-answer" class="epic-db-form">
	<?= $this->answerForm ?>
	<? if($this->answerForm && $this->answerForm->source): ?>
		<div class="wmd-preview post-text rounded" id="wmd-preview" style="display: none;">
			<h3>Preview of your answer...</h3>
		</div>    
		<script type="text/javascript">
			$(function(){
				// var markedit = $('#source').markedit({'preview': 'below'}).focus(function() { $("#wmd-preview").show(); });
				// $(markedit).markeditBindAutoPreview($('#wmd-preview'));
				// $(".markedit-preview").hide();
	  	});
	  </script>
	<? endif; ?>
</div>
